---
title: "Hallmark Ig-classes"
author: "vanBuggenum"
output:
  workflowr::wflow_html:
    toc: TRUE
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = F, warning = F, echo = T, eval = T,
  dev = c('png', 'pdf')
)
```

```{r libraries, include=FALSE}
source("code/load_packages.R")
library(MOFA2)
library(clusterProfiler)

panellabels <- c('A', 'B', 'C','D' , 'E', 'F', 'G', 'H', 'I', 'J', 'K')

add.textsize <- theme(axis.text.x = element_text(colour = 'black', size = 7),
          axis.text.y = element_text(colour = 'black',size=7),
          text = element_text(size=7),
          axis.text=element_text(size=7),
          plot.title = element_text(size=6)
          )


addSmallLegend <- function(myPlot = p, title_color =  "Avg. scaled\np-protein\nlevels", barheight = 2,barwidth = 0.2, pointSize = 0.8, textSize = 5.5, spaceLegend = 0.08) {
    myPlot +
        guides(color = guide_colorbar(barheight=barheight, barwidth = barwidth, title = title_color)) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}


colors.donors <- c("#999999", "#E69F00", "#56B4E9")
colors.clusters <-  c("#009E73", "#D55E00","#F0E442","grey")
```

```{r import}
seu.fix <- readRDS( file = "output/seu.fix_norm_plasmacells.rds")
seu.fix <- SetIdent(seu.fix,value = "IgClass")
Idents(seu.fix) <- factor(x = Idents(seu.fix), levels = c("IgM", "IgG", "IgA"))

seu.live <- readRDS(file = "output/seu.live_norm_plasmacells.rds")
seu.live <-SetIdent(seu.live,value = "IgClass")
Idents(seu.live) <- factor(x = Idents(seu.live), levels = c("IgM", "IgG", "IgA"))
```

To explore differences between three Ig-classes, we analyse protein and gene weights from the MOFA model and determine differential expressed genes or proteins. 

```{r import model}
# Read in the MOFA analysis file
mofa <- readRDS(file= "output/MOFA_analysis_Donorgroup_clustered.rds")

### Get all weights 
weights.RNA <- get_weights(mofa, views = "RNA",as.data.frame = TRUE)

weights.PROT.fix <- get_weights(mofa, views = "PROT.fix",as.data.frame = TRUE) %>%
  mutate(feature = gsub('.{2}$',x =  feature, replacement = '') )
weights.PROT.live <- get_weights(mofa, views = "PROT.live",as.data.frame = TRUE) %>%
  mutate(feature = gsub('.{2}$',x =  feature, replacement = '') )
weights.PROT.common <- get_weights(mofa, views = "PROT.common",as.data.frame = TRUE)

weights.protein <- rbind(weights.PROT.common,weights.PROT.live,weights.PROT.fix) %>%
  filter(factor == "Factor1" | factor == "Factor2") %>%
  spread(factor,value)

# Define lists of B cell selection, homing selection and diffgenes and diffprots
list.Bcell.selection <- c("CD25", "CD32", "CD20","CD19", "CD22", "CD40", "CD86") 
list.Bcell.selection.f <- c( "IgD", "CD23", "CD5", "CD70")
list.homing.selection.f <- c("CXCR4", "CXCR5","IntegrinA4")
list.homing.selection <- c("IntegrinB7", "IntegrinB1","CD49d", "CCR9", "CD31", "CD44","CXCR3")
list.Bcell.selection.new <- c( "CD138", "CD38", "CD27", "CD20","CD19")

# Read in the genelist for plots
genelist_plots_diffmarkers <- read_delim("data/genelist.plots.diffmarkers2.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

# Extract diffgenes and diffprots
list.genes.select.diffgenes <- c(unique(subset(genelist_plots_diffmarkers, modality == "RNA")$gene))
list.prot.select.diffprots <- c(unique(subset(genelist_plots_diffmarkers,  modality == "PROT")$gene))

# Concatenate the lists
list.dotplot.prots <- c(list.prot.select.diffprots,list.homing.selection,list.homing.selection.f,list.Bcell.selection.f,list.Bcell.selection)

# Add a new column with feature to plot
weights.protein <- weights.protein %>%
  mutate(features.toplot = ifelse(feature %in% c(list.dotplot.prots, "IgM", "IgA", "IgG"),as.character(feature),""))

```


### Fig.3


```{r scatter.plot.loadings.proteins}

view.labs <- c("Common proteins", "Live-cell proteins", "Fixed-cell proteins")
names(view.labs) <- c("PROT.common", "PROT.live", "PROT.fix")

p.loadings.scatter.prot <- 
ggplot(weights.protein, aes(Factor1, Factor2)) +
    geom_hline(yintercept = 0, color = "grey", alpha = 0.8)+
      geom_vline(xintercept = 0, color = "grey", alpha = 0.8)+
  geom_point(size = 0.5) +
  facet_wrap(~view,
              labeller = labeller(view = view.labs),
             scales = "free") +
  theme_few()+
  ggrepel::geom_text_repel( data          = subset(weights.protein, Factor1 > 10^-2 ),
                            aes(x=Factor1, y=Factor2, label=feature), size=1.8, max.overlaps = Inf,
     segment.size  = 0.15,
    segment.color = "grey50",
    direction     = "y",
    hjust         = 0)+
  
      ggrepel::geom_text_repel(
    data          = subset(weights.protein, Factor1 < -10^-2& Factor2 >10^-2 ),
    aes(x=Factor1, y=Factor2, label=feature), size=1.8, max.overlaps = Inf,
      segment.size  = 0.15,
    segment.color = "grey50",
    direction     = "y",
    hjust         = 1
  ) +
      ggrepel::geom_text_repel(
    data          = subset(weights.protein, Factor1 < -10^-2 & Factor2 <10^-2),
    aes(x=Factor1, y=Factor2, label=feature), size=1.8, max.overlaps = Inf,
     segment.size  = 0.15,
    segment.color = "grey50",
    direction     = "y",
    hjust         = 1
  )+
     add.textsize   +
    labs(title = "Protein loading values contributing to Factor 1 and 2\nrepresent IgM, IgG or IgA associated (phospho-)proteins ") +
  theme(
        panel.grid.major = element_blank(),
    panel.grid.minor = element_blank())

# p.loadings.scatter.prot

```

```{r list.IgAloadings}
topposrna.factor1.IgA <-  weights.RNA %>%
    spread(factor, value) %>%
  filter(Factor1 >= 10^-8) %>%
  select(c(feature, Factor1, Factor2)) %>%
  mutate(sortFactor1 = Factor1) %>%
  arrange(-sortFactor1)
  
rownames(topposrna.factor1.IgA) <- topposrna.factor1.IgA$feature

topposPROT.fix.factor1.IgA <- weights.PROT.fix %>%
    spread(factor, value) %>%
  filter(Factor1 >= 10^-8) %>%
  arrange(-Factor1)
rownames(topposPROT.fix.factor1.IgA) <- topposPROT.fix.factor1.IgA$feature

topposPROT.live.factor1.IgA <- weights.PROT.live %>%
    spread(factor, value) %>%
  filter(Factor1 >= 10^-8) %>%
  arrange(-Factor1)
rownames(topposPROT.live.factor1.IgA) <- topposPROT.live.factor1.IgA$feature

topposPROT.common.factor1.IgA <- weights.PROT.common %>%
    spread(factor, value) %>%
  filter(Factor1 >= 10^-8) %>%
  arrange(-Factor1)
rownames(topposPROT.common.factor1.IgA) <- topposPROT.common.factor1.IgA$feature


loadings.prot.IgA <- rbind(topposPROT.fix.factor1.IgA,topposPROT.live.factor1.IgA,topposPROT.common.factor1.IgA)
loadings.prot.IgA <- arrange(loadings.prot.IgA, -Factor1)
```

```{r IgMandIgG loadings}
topnegrna.factor2.IgM <- weights.RNA %>%
    spread(factor, value) %>%
  filter(Factor1 <= -10^-8) %>%
  filter(Factor2 <= -10^-8) %>%
  select(c(feature, Factor1, Factor2)) %>%
  mutate(sortminusFactor1times2 = -(Factor2*Factor1)) %>%
  arrange(sortminusFactor1times2)

rownames(topnegrna.factor2.IgM) <- topnegrna.factor2.IgM$feature

##filter for not IgA
##filter for not IgA
#topnegrna.factor2.IgM <-topnegrna.factor2.IgM[topnegrna.factor2.IgM$feature %in% topnegrna.factor1.IgMIgG$feature,]

topnegPROT.fix.factor2.IgM <- weights.PROT.fix %>%
  spread(factor, value) %>%
  filter(Factor1 <= -10^-7) %>%
  filter(Factor2 <= -10^-7) %>%
   arrange(Factor2)
rownames(topnegPROT.fix.factor2.IgM) <- topnegPROT.fix.factor2.IgM$feature

topnegPROT.live.factor2.IgM <- weights.PROT.live %>%
  spread(factor, value) %>%
  filter(Factor1 <= -10^-7) %>%
  filter(Factor2 <= -10^-7) %>%
  arrange(Factor2) 

rownames(topnegPROT.live.factor2.IgM) <- topnegPROT.live.factor2.IgM$feature

topnegPROT.common.factor2.IgM <- weights.PROT.common %>%
  spread(factor, value) %>%
  filter(Factor1 <= -10^-7) %>%
  filter(Factor2 <= -10^-7) %>%
  arrange(Factor2)
rownames(topnegPROT.common.factor2.IgM) <- topnegPROT.common.factor2.IgM$feature

loadings.prot.IgM <- rbind(topnegPROT.fix.factor2.IgM,topnegPROT.live.factor2.IgM,topnegPROT.common.factor2.IgM)
loadings.prot.IgM <- arrange(loadings.prot.IgM, -(Factor2*Factor1) )

topposrna.factor2.IgG <-weights.RNA %>%
    spread(factor, value) %>%
  filter(Factor1 <= -10^-8) %>%
  filter(Factor2 >= 10^-8) %>%
  select(c(feature, Factor1, Factor2)) %>%
  mutate(sortFactor2timesminus1 =  -(Factor2*-Factor1)) %>%
  arrange(sortFactor2timesminus1)
rownames(topposrna.factor2.IgG) <- topposrna.factor2.IgG$feature
##filter for not IgA
#topposrna.factor2.IgG <-topposrna.factor2.IgG[topposrna.factor2.IgG$feature %in% topnegrna.factor1.IgMIgG$feature,]

topposPROT.fix.factor2.IgG <- weights.PROT.fix %>%
    spread(factor, value) %>%
  filter(Factor1 <= -10^-7) %>%
  filter(Factor2 >= 10^-7) %>%
  arrange(-Factor2) 

rownames(topposPROT.fix.factor2.IgG) <- topposPROT.fix.factor2.IgG$feature

topposPROT.live.factor2.IgG <- weights.PROT.live %>%
    spread(factor, value) %>%
  filter(Factor1 <= -10^-7) %>%
  filter(Factor2 >= 10^-7) %>%
  arrange(-Factor2) 

rownames(topposPROT.live.factor2.IgG) <- topposPROT.live.factor2.IgG$feature

topposPROT.common.factor2.IgG <- weights.PROT.common %>%
    spread(factor, value) %>%
  filter(Factor1 <= -10^-7) %>%
  filter(Factor2 >= 10^-7) %>%
  arrange(-Factor2)
rownames(topposPROT.common.factor2.IgG) <- topposPROT.common.factor2.IgG$feature

loadings.prot.IgG <- rbind(topposPROT.fix.factor2.IgG,topposPROT.live.factor2.IgG,topposPROT.common.factor2.IgG)
loadings.prot.IgG <- arrange(loadings.prot.IgG, -(Factor2*-Factor1))

loadings.prot.IgM <- select(loadings.prot.IgM, c(feature, view, Factor1, Factor2))
loadings.prot.IgG <- select(loadings.prot.IgG, c(feature, view, Factor1, Factor2))
loadings.prot.IgA <- select(loadings.prot.IgA, c(feature, view, Factor1, Factor2))

# write_tsv(loadings.prot.IgM, file = "output/top-PROT-loadings_IgM.tsv")
# write_tsv(loadings.prot.IgA, file = "output/top-PROT-loadings_IgA.tsv")
# write_tsv(loadings.prot.IgG, file = "output/top-PROT-loadings_IgG.tsv")


```

```{r listloadings}

# write_tsv(topnegrna.factor2.IgM, file = "output/top-gene-loadings_IgM.tsv")
# write_tsv(topposrna.factor1.IgA, file = "output/top-gene-loadings_IgA.tsv")
# write_tsv(topposrna.factor2.IgG, file = "output/top-gene-loadings_IgG.tsv")

list.genes.loadings.top20 <- rev(c(as.character(topnegrna.factor2.IgM$feature[1:20]),as.character(topposrna.factor1.IgA$feature[1:20]),as.character(topposrna.factor2.IgG$feature[1:20])))

list.genes.loadings.top200 <- rev(c(as.character(topnegrna.factor2.IgM$feature[1:200]),as.character(topposrna.factor2.IgG$feature[1:200]), as.character(topposrna.factor1.IgA$feature[1:200])))

list.genes.loadings.top200 <- rev(c(as.character(topnegrna.factor2.IgM$feature[1:200]),as.character(topposrna.factor2.IgG$feature[1:200]), as.character(topposrna.factor1.IgA$feature[1:200])))

list.genes.loadings.all <- rev(c(as.character(topnegrna.factor2.IgM$feature),as.character(topposrna.factor2.IgG$feature), as.character(topposrna.factor1.IgA$feature)))

```

```{r plot.panels.dotplots.mainfigure3}

All.diff.PROT.live <- unique(c(as.character(loadings.prot.IgM$feature),as.character(loadings.prot.IgG$feature),as.character(loadings.prot.IgA$feature)))
All.diff.PROT.fix <- unique(c(as.character(loadings.prot.IgM$feature),as.character(loadings.prot.IgG$feature),as.character(loadings.prot.IgA$feature)))

p.dotplot.Bcell.markers.l <- DotPlot(seu.live,assay = "PROT",features = rev(sort((All.diff.PROT.live[All.diff.PROT.live %in%list.Bcell.selection.new] ))), cols = "RdBu",dot.scale = 3, scale.min = 0, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Proteins \n(live)", y = "", title = "B-cell markers expression \nsurface-proteins") +
  add.textsize +
  theme(legend.position = "none", 
        legend.key.size = unit(2, 'mm'),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(angle=0, hjust=1))

p.dotplot.Bcell.markers.f <- DotPlot(seu.fix,assay = "PROT",features = rev(c(All.diff.PROT.fix[All.diff.PROT.fix%in%list.Bcell.selection.f] )) , cols = "RdBu",dot.scale = 3, scale.min = 0, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Proteins (fixed)", y = "") +
  add.textsize +
  theme(legend.position = "none", 
        legend.key.size = unit(2, 'mm'),
        axis.text.y = element_text(angle=0, hjust=1))



p.dotplot.gene.diff.gene <- DotPlot(seu.live,assay = "SCT",features =sort(unique(list.genes.loadings.all[list.genes.loadings.all %in%list.genes.select.diffgenes])) , cols = "RdBu",dot.scale = 3, scale.min = 0, scale.max = 100, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Selected differentiation \ngenes", y = "", title = "PC differentiation markers \nand regulators")  +
  add.textsize +
  theme(legend.position = "none", 
        axis.text.y = element_text(angle=0, hjust=1,face = "italic"), 
        legend.key.size = unit(2, 'mm'),
        axis.text.x = element_text(angle=0, hjust=0.5),
        legend.box="vertical", legend.margin=margin())

p.dotplot.gene.diff.prot.f <- DotPlot(seu.fix,assay = "PROT",features = sort((All.diff.PROT.fix[All.diff.PROT.fix%in%list.prot.select.diffprots])) , cols = "RdBu",dot.scale = 3, scale.min = 0,   scale.max= 100, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Proteins  \n(fixed)", y = "", title = "") +
  add.textsize +
  theme(legend.position = "none", 
        legend.key.size = unit(2, 'mm'),
        axis.text.y = element_text(angle=0, hjust=1))

p.dotplot.Diff.markers <- plot_grid(p.dotplot.gene.diff.gene,p.dotplot.gene.diff.prot.f, ncol = 1, rel_heights = c(1.15,1.35))

p.dotplot.prot.TACI <- DotPlot(seu.live,assay = "PROT",features = unique(c("CD40", "CD70", "CD27", "BCMA", "TACI","BAFFR")[c("CD40", "CD70", "CD27", "BCMA", "TACI","BAFFR") %in%All.diff.PROT.fix]) , cols = "RdBu",dot.scale = 3, scale.min = 0, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Proteins \n(live)", y = "", title = "TACI-BCMA-BAFFR \nmembrane-protein levels")  +  
  add.textsize +
  theme(legend.position = "none", 
        legend.key.size = unit(2, 'mm'),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(angle=0, hjust=1))

p.dotplot.gene.homing.l <- DotPlot(seu.live,assay = "PROT",features = unique(list.homing.selection[list.homing.selection %in%All.diff.PROT.live]) , cols = "RdBu",dot.scale = 3, scale.min = 0, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Proteins \n(live)", y = "", title = "Homing receptors expression \n surface-proteins")  +  
  add.textsize +
  theme(legend.position = "none", 
        legend.key.size = unit(2, 'mm'),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(angle=0, hjust=1))

p.dotplot.gene.homing.f <- DotPlot(seu.fix,assay = "PROT",features = list.homing.selection.f[list.homing.selection.f %in%All.diff.PROT.fix], cols = "RdBu",dot.scale = 3,  scale.min = 0, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Proteins \n(fixed)", y = "")  +
  theme(legend.position = "bottom", 
        legend.key.size = unit(2, 'mm'),
        axis.text.x = element_text(angle=0, hjust=0.5),
        legend.box="vertical", legend.margin=margin(),
        axis.text.y = element_text(angle=0, hjust=1))+
  add.textsize #

p.dotplot.Bcell.markers <- plot_grid(p.dotplot.Bcell.markers.l,p.dotplot.prot.TACI,labels = panellabels[c(2,4)], label_size = 10, ncol = 1,rel_heights = c(1,1.2))

p.dotplot.gene.homing.f <- addSmallLegend(p.dotplot.gene.homing.f, barwidth =4, barheight = 0.2, title_color = "Avg. scaled \ncounts", spaceLegend = 0.001)

p.dotplot.gene.homing<- plot_grid( p.dotplot.gene.homing.l,p.dotplot.gene.homing.f, ncol = 1, rel_heights = c(1.6,1.4), labels = panellabels[c(5)], label_size = 10) 



```

```{r create.fig3}
p.Fig3.row1 <- plot_grid(p.loadings.scatter.prot, labels = panellabels[c(1)], label_size = 10, ncol =1, rel_widths = c(1))
# ggsave(p.Fig3.row1, filename = "output/paper_figures/Fig3.A.pdf", width = 177, height = 80, units = "mm",  dpi = 300, useDingbats = FALSE)
# ggsave(p.Fig3.row1, filename = "output/paper_figures/Fig3.A.png", width = 177, height = 80, units = "mm",  dpi = 300)

p.Fig3.row2 <- plot_grid(p.dotplot.Bcell.markers,p.dotplot.Diff.markers,
p.dotplot.gene.homing, labels = c("",panellabels[c(3)]), label_size = 10, ncol =3, rel_widths = c(1,0.8,1.2))
# ggsave(p.Fig3.row2, filename = "output/paper_figures/Fig3.BCD.pdf", width = 177, height = 120, units = "mm",  dpi = 300, useDingbats = FALSE)
# ggsave(p.Fig3.row2, filename = "output/paper_figures/Fig3.BCD.png", width = 177, height = 120, units = "mm",  dpi = 300)
```

```{r Figure3.row1, fig.width=7.2, fig.height=3}
p.Fig3.row1
```

```{r Figure3.row2, fig.width=7.2, fig.height=4.7}
p.Fig3.row2
```



### Fig.4

```{r plots.cytokinereceptors}
## plots cytokinereceptors

cytokinerecept.list <- c("IL2RA", "IL2RB","IL2RG", "IL6R", "IL15RA", "IFNAR1", "IFNAR2")

p.dotplot.gene.cytokinerecept <- DotPlot(seu.live,assay = "SCT",features = c(rev(cytokinerecept.list)), cols = "RdBu",dot.scale = 3, scale.min = 0, scale = T, scale.by = "size", col.min = -0.5, col.max = 0.5)+coord_flip() +
  labs(x = "Gene", y = "", title = "Cytokine receptor \nmRNA expression") +
  add.textsize+
    guides(size =  guide_legend(title = "Percent \nexpressed"),color = guide_colorbar(title = "Avg. scaled\nexpression"))
#+  guides(size = "none",color = "none")

p.vln.prot.cytokinerecept.IL6R <- VlnPlot(seu.live, assay = "PROT",features = c("IL6"), pt.size = 0, cols = colors.clusters, ncol = 1, log = T) +
  stat_summary(fun.y = median, geom='point', size = 2.5, colour = "black", shape = 95) &
  labs(x = "", y = "IL6R protein (log)", title = "") &
  add.textsize  +
  theme(legend.position = "none", 
        legend.key.size = unit(2, 'mm'),
        axis.text.x = element_text(angle=0, hjust=0.5),
        plot.title = element_blank())
   

p.vln.prot.cytokinerecept.IL2R <- VlnPlot(seu.live, assay = "PROT",features = c("CD25"), pt.size = 0, cols = colors.clusters, ncol = 1, log = T) & 
  stat_summary(fun.y = median, geom='point', size = 2.5, colour = "black", shape = 95) &
  labs(x = "", y = "IL2R protein (log)", title = "Cytokine receptors \nprotein expression") &
  add.textsize +
  theme(legend.position = "none", 
        legend.key.size = unit(2, 'mm'),
        axis.text.x = element_text(angle=0, hjust=0.5))
   
p.vln.prot.cytokinerecept <- p.vln.prot.cytokinerecept.IL2R/p.vln.prot.cytokinerecept.IL6R

p.cytokinerecept.levels <- p.dotplot.gene.cytokinerecept +p.vln.prot.cytokinerecept


#### JAKSTAT

toplot.prot <- c("pJAK1","pSTAT1", "pSTAT3","pSTAT5", "pSTAT6")

p.dotplot.JAKSTAT.PROT <-  DotPlot(seu.fix,assay = "PROT",features = rev(toplot.prot), cols = "RdBu",dot.scale = 3, scale.min = 0, scale = T, scale.by = "size")+
  coord_flip() +
  labs(x = "Intracellular phosphorylation", y = "", title = "Ig-specific JAK-STAT activity \nphospho-protein levels") +
  add.textsize +
    guides(size =  guide_legend(title = "Percent \nexpressed"),color = guide_colorbar(title = "Avg. scaled\np-protein\nlevels"))

toplot.RNA <- c("STAT1", "STAT3","PRDM1", "STAT6")

p.dotplot.JAKSTAT.RNA <-  DotPlot(seu.live,assay = "SCT",features = rev(toplot.RNA), cols = "RdBu",col.min = -0.5,col.max = 0.5,dot.scale = 3, scale.min = 0, scale = T, scale.by = "size")+
  coord_flip() +
  labs(x = "Transcription Factor (RNA expression)", y = "", title = "Ig-specific STAT \nmRNA expression") +
  add.textsize +
    guides(size =  guide_legend(title = "Percent \nexpressed"),color = guide_colorbar(title = "Avg. scaled\nexpression"))
#+  guides(size = "none",color = "none")


p.JAKSTAT <- p.dotplot.JAKSTAT.RNA +p.dotplot.JAKSTAT.PROT 


#### BCR activity

p.MOFA.factors.cluster <-  plot_factors(mofa, 
   factors =c(1:2),
  color_by = "IgClass",
  dot_size = 1.2
) +labs(x = "Factor 1", y = "Factor 2", title = "Differential BCR signaling activity \nacross three Ig-classes", color = "Ig-class") +
scale_fill_manual("Cluster",values= colors.clusters) +
  add.textsize&
    theme_half_open()& 
  theme(legend.position = c(0.85,0.95), legend.key.size = unit(2, 'mm')) &
  theme(axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          text = element_text(size=7), axis.ticks = element_blank(),
          axis.text=element_text(size=7),
          plot.title = element_text(size=7, face = "bold",hjust = 0)) 


p.MOFA.factors.CD79a <- plot_factors(mofa, 
  factors = c(1:2),
  color_by = "pCD79a_f",dot_size = 1.2,show_missing = FALSE
) &
    add.textsize &  
  labs(x = "Factor 1", y = "Factor 2", fill = "Scaled \ncounts", title = "pCD79a\nlevels") &
  theme_half_open()& 
  theme(legend.position = c(0.85,0.95), legend.key.size = unit(2, 'mm')) &
  theme(axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          text = element_text(size=7), axis.ticks = element_blank(),
          axis.text=element_text(size=7),
          plot.title = element_text(size=7, face = "bold",hjust = 0)) &
  scale_fill_gradient2( limits = c(-1, 1),low="dodgerblue3", mid="white", high="firebrick3",  oob = scales::squish)

p.dotplot.BCR.sign.phospho <- DotPlot(seu.fix,assay = "PROT", features =  rev(c("pCD79a",  "pBLNK", "pSrc", "pp38","pSyk","pp65", "pJNK", "p-c-Jun", "pTOR", "pAMPKb1", "pIKKab")), cols = "RdBu",dot.scale = 2,scale.min = 0, scale.max = 100, scale = T, scale.by = "size", col.min = -1, col.max = 1)+ 
  cowplot::theme_cowplot() + 
  coord_flip()+
  add.textsize +
  labs(x = "BCR signaling", y = "", title ="B-cell receptor related \nsignalling activity") +
  theme(legend.position = "right", legend.key.size = unit(2, 'mm')) +
    guides(size =  guide_legend(title = "Percent \nexpressed"),color = guide_colorbar(title = "Avg. scaled\np-protein\nlevels"))
```

```{r Fig4, fig.width=7.2, fig.height=5.9}

p.cytokine_JAKSTAT <- plot_grid( 
              addSmallLegend(p.dotplot.gene.cytokinerecept, title_color = "Avg. scaled \nexpression"),
              p.vln.prot.cytokinerecept,
              addSmallLegend(p.dotplot.JAKSTAT.RNA, title_color = "Avg. scaled \nexpression"),
              addSmallLegend(p.dotplot.JAKSTAT.PROT),
            labels = c(panellabels[c(1:4)]), label_size = 10, ncol =4,rel_widths = c(1,0.6,1,1))


p.BCR <- plot_grid(p.MOFA.factors.cluster, p.MOFA.factors.CD79a,addSmallLegend(p.dotplot.BCR.sign.phospho), labels = c(panellabels[c(5)], "",panellabels[c(6:7)]), label_size = 10, ncol =3,rel_widths = c(1,1.25,1))

fig.4.signalling <- plot_grid(p.cytokine_JAKSTAT, p.BCR, labels = "", label_size = 10, ncol =1,rel_heights = c(1.2,1))


# ggsave(fig.4.signalling, filename = "output/paper_figures/Fig4.pdf", width = 177, height = 150, units = "mm",  dpi = 300, useDingbats = FALSE)
# ggsave(fig.4.signalling, filename = "output/paper_figures/Fig4.png", width = 177, height = 150, units = "mm",  dpi = 300)

fig.4.signalling
```

### Differential geneexpression per Ig-class (suppl)

```{r classspecific.genemarkers}
## RNA sign Differences

markers.OnevsAll <- FindAllMarkers(seu.live, assay = "SCT", logfc.threshold = 0.01, test.use = "wilcox", only.pos = T, verbose = T)
markers.OnevsAll <- filter(markers.OnevsAll, p_val <= 0.05)
markers.IgMvsAll <- filter(markers.OnevsAll, cluster == "IgM")
markers.IgAvsAll <- filter(markers.OnevsAll, cluster == "IgA")
markers.IgGvsAll <- filter(markers.OnevsAll, cluster == "IgG")

markers.IgAvsAll.list <- unique(replace(rownames(markers.IgAvsAll), rownames(markers.IgAvsAll)=="JCHAIN1", "JCHAIN"))
markers.OnevsAll.list <- unique(replace(rownames(markers.OnevsAll), rownames(markers.OnevsAll)=="JCHAIN1", "JCHAIN"))
```


```{r plot.diff.gene.dotplot}
p.dotplot.diff.genes.all <- DotPlot(seu.live,assay = "SCT", features =  rev(markers.OnevsAll.list), group.by =  "clusters_pcaIG_named", cols = "RdBu",dot.scale = 2,scale.min = 0, scale.max = 100, scale = T, scale.by = "size", col.min = -1, col.max = 1) +
  cowplot::theme_cowplot() + 
  coord_flip()+
  add.textsize +
  theme(legend.position = "right", legend.key.size = unit(2, 'mm'))

p.dotplot.diff.genes.IgM <- DotPlot(seu.live,assay = "SCT", features =  rev(rownames(markers.IgMvsAll)),split.by = "donor", cols = "RdBu",dot.scale = 2,scale.min = 0, scale.max = 100, scale = T, scale.by = "size", col.min = -1, col.max = 1) +
  cowplot::theme_cowplot() + 
  coord_flip()+
  add.textsize +
  theme(legend.position = "none", legend.key.size = unit(2, 'mm'))+
  labs(title="IgM versus others (88 genes)",x="Differential expressed genes (p-val < 0.05, logfc >= 0.01)", y = "") +
  scale_y_discrete(labels = c("D32 \n","D33 \nIgM", "D40","D32 \n","D33 \nIgG", "D40","D32 \n","D33 \nIgA", "D40"))

p.dotplot.diff.genes.IgA <- DotPlot(seu.live,assay = "SCT", features =  rev(markers.IgAvsAll.list),split.by = "donor", cols = "RdBu",dot.scale = 2,scale.min = 0, scale.max = 100, scale = T, scale.by = "size", col.min = -1, col.max = 1) +
  cowplot::theme_cowplot() + 
  coord_flip()+
  add.textsize +
  theme(legend.position = "none", legend.key.size = unit(2, 'mm'))+
  labs(title="IgA versus others (28 genes)",x="Differential expressed genes (p-val < 0.05, logfc >= 0.01)", y = "")+
  scale_y_discrete(labels = c("D32 \n","D33 \nIgM", "D40","D32 \n","D33 \nIgG", "D40","D32 \n","D33 \nIgA", "D40"))

p.dotplot.diff.genes.IgG <- DotPlot(seu.live,assay = "SCT", features =  rev(rownames(markers.IgGvsAll)),split.by = "donor", cols = "RdBu",dot.scale = 2,scale.min = 0, scale.max = 100, scale = T, scale.by = "size", col.min = -1, col.max = 1) +
  cowplot::theme_cowplot() + 
  coord_flip()+
  add.textsize +
  theme(legend.position = "right", legend.key.size = unit(2, 'mm'))+
  labs(title="IgG versus others (67 genes)",x="Differential expressed genes (p-val < 0.05, logfc >= 0.01)", y = "")+
  scale_y_discrete(labels = c("D32 \n","D33 \nIgM", "D40","D32 \n","D33 \nIgG", "D40","D32 \n","D33 \nIgA", "D40"))

```

```{r, fig.width=7.2, fig.height=10}
p.suppl.diff.genes <- plot_grid(p.dotplot.diff.genes.IgM,p.dotplot.diff.genes.IgG, p.dotplot.diff.genes.IgA,ncol = 2, rel_widths = c(1,1.3), rel_heights = c(1,0.7), labels = panellabels[1:3], label_size = 10)


# ggsave(p.suppl.diff.genes, filename = "output/paper_figures/p.suppl.diff.genes.pdf", width = 183, height = 320, units = "mm",  dpi = 300, useDingbats = FALSE)
# ggsave(p.suppl.diff.genes, filename = "output/paper_figures/p.suppl.diff.genes.png", width = 183, height = 320, units = "mm",  dpi = 300)
p.suppl.diff.genes
```
